# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' invls_calc
#'
#' This function returns a numeric matrix identifying
#' matching values from a raster that intersect with
#' a set of points
#' @export
invls_calc <- function(lsm, resolution, xmin, ymax, s, direction, slr, slr_xmin, slr_xmax, slr_ymin, slr_ymax) {
    .Call('_microclima_invls_calc', PACKAGE = 'microclima', lsm, resolution, xmin, ymax, s, direction, slr, slr_xmin, slr_xmax, slr_ymin, slr_ymax)
}

basinCpp <- function(dm2, bsn, dun) {
    .Call('_microclima_basinCpp', PACKAGE = 'microclima', dm2, bsn, dun)
}

renumberbasin <- function(m, u) {
    .Call('_microclima_renumberbasin', PACKAGE = 'microclima', m, u)
}

